typography_spectrum: 0.05099941254593432
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.045297417091205716
  lightness: 0.5634260650258511
  saturation: 0.304550860542804
  rhythmicContrast: 0.20236603100784123
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7745903341565281
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: robert.engels
  email: info@esis.no
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/514bf998-60e4-448e-8d1a-d772f930ca1a.png
name: ESIS Norge AS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Artificial Intelligence & Machine Learning
description: your source for consultancy on disruptive technologies
purpose: []
